scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ............................................................................................................c...................................................
    ............................................................................................................c...................................................
    ...........................................................................................................cc...................................................
    ...................1.......................................................................................cc...................................................
    ...................1......................................................................................c.c...................................................
    ...................1......................................................................................c.c...................................................
    ..................11......................................................................................c.c...................................................
    ..................11......................................................................................c.c...................................................
    ..................11......................................................................................c.c...................................................
    .................111......................................................................................c.c...................................................
    ..........1......1111.....................................................................................c.c...................................................
    ...........11111111111....................................................................................c.c...................................................
    .............11111111111.................................................................................ccc....................................................
    ..............11111......................................................................................ccc....................................................
    ................111......................................................................................ccc....................................................
    .................11.....................................................................................cccc....................................................
    ....................................................c...................................................cccc....................................................
    ....................................................c...................................................cccc....................................................
    ....................................................c...................................................cccc....................................................
    ...................c................................c..................................................ccccc....................................................
    ...................c................................c..................................................ccccc....................................................
    ...................c................................c..................................................ccccc....................................................
    ...................c................................c..................................................ccccc....................................................
    ...................c................................c.................................................cccccc....................................................
    ..................cc...............................cc.................................................cccccc............................................c.......
    ..................cc...............................cc.................................................cccccc...........................................cc.......
    ..................cc...............................cc.................................................cccccc...........................................cc.......
    ..................cc...............................c.................................................ccccccc...........................................cc.......
    ..................cc...............................c.................................................ccccccc...........................................cc.......
    ..................cc..............................cc.................................................ccccccc...........................................c........
    ..................cc..............................cc.................................................ccccccc..........................................cc........
    ..................cc..............................cc.................................................ccccccc..........................................cc........
    ..................cc..............................cc................................................cccccccc.........................................ccc........
    ..................cc..............................cc................................................cccccccc.........................................ccc........
    ..................cc..............................cc................................................cccccccc........................................cccc........
    ..................cc.............................c.c................................................cccccccc........................................cccc........
    ..................c..............................c.c................................................cccccccc........................................cccc........
    ..................c..............................c.c...............................................ccccccccc.......................................ccccc........
    ..................c..............................cc................................................ccccccccc.......................................ccccc........
    ..................c..............................cc................................................ccccccccc.......................................ccccc........
    ..................c..............................cc................................................ccccccccc.......................................ccccc........
    ..................c.............................ccc...............................................cccccccccc......................................cccccc........
    ..................c.............................ccc...............................................ccccccccccc.....................................cccccc........
    ..................c.............................ccc...............................................ccccccccccc.....................................cccccc........
    .................cc.............................ccc...............................................ccccccccccc....................................ccccccc........
    .................cc............................cccc..............................................cccccccccccc....................................ccccccc........
    .................cc............................cccc..............................................cccccccccccc...................................cccccccc........
    .................cc............................cccc..............................................ccccccccccccc..................................ccccccc.........
    ................ccc...........................ccccc..............................................ccccccccccccc.................................cccccccc.........
    ................ccc...........................ccccc..............................................ccccccccccccc.................................cccccccc.........
    ................ccc...........................ccccc..............................................ccccccccccccc.................................cccccccc.........
    ...............cccc...........................cccccc.............................................cccccccccccccc...............................ccccccccc.........
    ...............cccc..........................ccccccc.............................................ccccccccccccccc..............................ccccccccc.........
    ...............cccc..........................ccccccc............................................cccccccccccccccc.............................cccccccccc.........
    ...............cccc.........................ccccccccc...........................................ccccccccccccccccc............................cccccccccc.........
    ..............ccccc.........................ccccccccc........................22222..............cccccccccccccccccc..........................ccccccccccc.........
    ..............ccccc........................cccccccccc.....................222222222.............ccccccccccccccccccc.........................ccccccccccc.........
    ..............cccccc.......................cccccccccc...................222222222222............cccccccccccccccccccc.......................cccccccccccc.........
    .............ccccccc.......................ccccccccccc.................22222222222222...........ccccccccccccccccccccc.....................ccccccccccccc.........
    .............ccccccc......................cccccccccccc................222222222222222...........cccccccccccccccccccccc....................ccccccccccccc.........
    .............cccccccc.....................ccccccccccccc..............2222222222222222..........cccccccccccccccccccccccc..................ccccccccccccccc........
    .............cccccccc....................ccccccccccccccc............222222222222222222.........ccccccccccccccccccccccccc................cccccccccccccccc........
    ............cccccccccc...................ccccccccccccccc.............22222222222222222........ccccccccccccccccccccccccccccc............ccccccccccccccccc........
    ............cccccccccc..................ccccccccccccccccc............22222222222222222........cccccccccccccccccccccccccccccc...........ccccccccccccccccc........
    ...........ccccccccccc..................ccccccccccccccccc...........22222222222222222.........cccccccccccccccccccccccccccccc..........cccccccccccccccccc........
    ...........cccccccccccc................ccccccccccccccccccc..........2222222222222222.........cccccccccccccccccccccccccccccccc........cccccccccccccccccccc.......
    ..........ccccccccccccc...............ccccccccccccccccccccc.........2222222222222222.........cccccccccccccccccccccccccccccccc........cccccccccccccccccccc.......
    ..........ccccccccccccc...............cccccccccccccccccccccc........2222222222222222........cccccccccccccccccccccccccccccccccc.......ccccccccccccccccccccc......
    ..........cccccccccccccc.............cccccccccccccccccccccccc.......2222222222222222........ccccccccccccccccccccccccccccccccccc.....cccccccccccccccccccccc......
    .........ccccccccccccccc.............cccccccccccccccccccccccc......22222222222222222.......cccccccccccccccccccccccccccccccccccc.....ccccccccccccccccccccccc.....
    .........ccccccccccccccc............ccccccccccccccccccccccccccc....2222222222222222........ccccccccccccccccccccccccccccccccccccc...cccccccccccccccccccccccc.....
    ........cccccccccccccccc...........cccccccccccccccccccccccccccccc..2222222222222222.......ccccccccccccccccccccccccccccccccccccccc.cccccccccccccccccccccccccc....
    ........ccccccccccccccccc.........cccccccccccccccccccccccccccccccc.2222222222222222.......ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc...
    .......cccccccccccccccccc........ccccccccccccccccccccccccccccccccccc222222222222222.......cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ......cccccccccccccccccccc......ccccccccccccccccccccccccccccccccccc222222222222222......cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ......ccccccccccccccccccccc....cccccccccccccccccccccccccccccccccccc222222222222222.....ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    .....cccccccccccccccccccccc...ccccccccccccccccccccccccccccccccccccc222222222222222...ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ....ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc22222222222222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ....ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc22222222222222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ...cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2222222222222cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ..ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2222222222222cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    .cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc222222222222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc222222222222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc22222222222cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2222222222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc22222222cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2222222cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc222ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    `)
tiles.setCurrentTilemap(tilemap`level0`)
let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . e e e . . . . . . . . . . . 
    . . e 1 e e e f f f . . . . . . 
    . . e e 1 1 e f 5 f f . . . . . 
    . . . e e 1 1 f f f . . . . . . 
    . . . . e e f f f . . . . . . . 
    . . . . . e f f f . . . . . . . 
    . . . . . . f f f . . . . . . . 
    . . . . . . f . f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
